INSERT INTO I_CRM_APPLICATION(
       application_id           -- bigint NOT NULL,
       ,application_id_src      -- nvarchar(100) NULL,
       ,src_name                -- nvarchar(100) NULL,
       ,creation_date           -- datetime NULL,
       ,statecode               -- nvarchar(10) NULL,
       ,surname                 -- nvarchar(100) NULL,
       ,name                    -- nvarchar(100) NULL,
       ,patronymic              -- nvarchar(100) NULL,
       ,phone                   -- nvarchar(20) NULL,
       ,email                   -- nvarchar(100) NULL,
       ,doc_type                -- nvarchar(100) NULL,
       ,doc_series              -- nvarchar(20) NULL,
       ,doc_number              -- nvarchar(50) NULL,
       ,issue_date              -- date NULL,
       ,income                  -- money NULL,
       ,object_cost             -- money NULL,
       ,cost_currency           -- nvarchar(100) NULL,
       ,credit_amount           -- money NULL,
       ,term                    -- int NULL,
       ,rate                    -- numeric(10, 6) NULL,
       ,schedule                -- nvarchar(100) NULL,
       ,contribution            -- numeric(10, 6) NULL,
)
VALUES (
        123322232           -- bigint NOT NULL,
       ,'credit_assist'      -- nvarchar(100) NULL,
       ,'Кредитный помощник'                -- nvarchar(100) NULL,
       ,'2012-08-09 21:38:06.430'           -- datetime NULL,
       ,'3347780927'               -- nvarchar(10) NULL,
       ,'Кукуцаполь'                 -- nvarchar(100) NULL,
       ,'Кришна'                    -- nvarchar(100) NULL,
       ,'Олимпиада'              -- nvarchar(100) NULL,
       ,'380631003256'                   -- nvarchar(20) NULL,
       ,'sava@mail.dot.com'                   -- nvarchar(100) NULL,
       ,"passport"                -- nvarchar(100) NULL,
       ,"СА"              -- nvarchar(20) NULL,
       ,"215523"              -- nvarchar(50) NULL,
       ,"2012-08-09"              -- date NULL,
       ,"12000"                  -- money NULL,
       ,"129000"             -- money NULL,
       ,"UAH"           -- nvarchar(100) NULL,
       ,"100000"           -- money NULL,
       ,"48"                    -- int NULL,
       ,"18"                    -- numeric(10, 6) NULL,
       ,"schedule"                -- nvarchar(100) NULL,
       ,"contribution"            -- numeric(10, 6) NULL,

)

